# Generated by Django 5.1.3 on 2025-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(default='', max_length=400)),
                ('Company', models.CharField(default='', max_length=100)),
                ('Place', models.CharField(default='', max_length=40)),
                ('Email', models.CharField(default='', max_length=20)),
                ('Phone', models.IntegerField(default='')),
            ],
        ),
    ]
